services:
  gateway-service:
    build:
      context: ./backend
      dockerfile: gateway/Dockerfile
      target: ${BUILD_TARGET}
    environment:
      - APP_MODE=${APP_MODE}
    volumes:
      - ./backend/config.json:/app/config.json:ro
      - ./backend/gateway:/app
    ports:
      - "8080:8080"
    networks:
      - dc20clerk-net

  identity-service:
    build:
      context: ./backend
      dockerfile: identity/Dockerfile
      target: ${BUILD_TARGET}
    environment:
      - APP_MODE=${APP_MODE}
    volumes:
      - ./backend/config.json:/app/config.json:ro
      - ./backend/identity:/app
    ports:
      - "8081:8081"
    networks:
      - dc20clerk-net
    depends_on:
      - gateway-service

  frontend:
    build:
      context: ./frontend
      target: ${BUILD_TARGET}
    command: /bin/sh -c "if [ \"$APP_MODE\" = \"dev\" ]; then npm run dev; else npm run build && serve -s build; fi"
    environment:
      - APP_MODE=${APP_MODE}
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - dc20clerk-net
    depends_on:
      - gateway-service

networks:
  dc20clerk-net:
    driver: bridge
